### ISSUE TITLE
As a guest, I want to be able to view talent information as a list on the home page and see a limited information.

### ISSUE THREAD

**Issue by asya982** [Team-Alexander/frontend#1]
## Acceptance criteria
1.1 The following information should be displayed
- Photo;
- Last name, first name;
- Banner;
- Skills
1.2. Guest cannot see full info about a talent

##### Front-end
- [x] #5
- [x] #6
- [x] #22
- [x] #7
- [x] #18 
##### Back-end
- [x] https://github.com/Team-Alexander/backend/issues/1
- [x] https://github.com/Team-Alexander/backend/issues/8

**Comment by DmytroTeliukov** [comment]
- [ ] List of talents api
