### ISSUE TITLE
2.1 Create Talent profile component

### ISSUE THREAD

**Issue by asya982** [Team-Alexander/frontend#10]
### Description

1. Create component of profile with all info about talent
2. Create link to this form on the button in General talant component

#### Design

![Image](https://user-images.githubusercontent.com/114294333/226112527-7e4cea06-17d7-41a5-b4df-9ef34e90884d.png)

[Link to Figma](https://www.figma.com/file/XOIDAKeJY6P6Rr4JUTPr2D/UpTalent?node-id=0%3A1&t=ECIUiF5mMXX9XBVM-1)

**Comment by Miroslav-Shashkin** [comment]
@asya982 Bug report: http://surl.li/fwwmv
