### ISSUE TITLE
0.3 Create Header component

### ISSUE THREAD

**Issue by ira-bibik** [Team-Alexander/frontend#11]
### Desription

1. Logo (link to homepage)
2. Buttons log in/sign up (guest)
3. Profile(if talent)

#### Design

![Image](https://user-images.githubusercontent.com/114294333/226350953-7aec4d96-5f72-4529-8d46-f4908262e117.png)

![Image](https://user-images.githubusercontent.com/114294333/226349398-1782bb53-9fb6-4588-ba78-353658a5e1e9.png)

[Link to Figma](https://www.figma.com/file/XOIDAKeJY6P6Rr4JUTPr2D/UpTalent?node-id=0%3A1&t=ECIUiF5mMXX9XBVM-1)

**Comment by Miroslav-Shashkin** [comment]
[https://uptalent.atlassian.net/browse/U0-24?atlOrigin=eyJpIjoiMmVhMmIzYTdjZmU5NDliMGE2NTY5MjJhMzk5M2ZlODciLCJwIjoiaiJ9](url)

**Comment by Miroslav-Shashkin** [comment]
@ira-bibik Bug report : http://surl.li/fwwkp

**Comment by Miroslav-Shashkin** [comment]
@ira-bibik 

- [ ] Bug-17: https://uptalent.atlassian.net/browse/U0-51?atlOrigin=eyJpIjoiNjMzMTkyOGRiMzFkNGJlZDhlMzlkM2RkN2NkNWEzY2UiLCJwIjoiaiJ9
