### ISSUE TITLE
4.3.1 Skills in Talent's profile

### ISSUE THREAD

**Issue by asya982** [Team-Alexander/frontend#169]
### Description

1. Make skills not required on registration form
2. Change requests up to modified endpoints(get talents/talentId, patch)

**Comment by Miroslav-Shashkin** [comment]
@ira-bibik @asya982 
- [x] Bug-61 : https://uptalent.atlassian.net/browse/U0-115
- [x] Bug-63 : https://uptalent.atlassian.net/browse/U0-118
- [ ] Bug-104 : https://uptalent.atlassian.net/browse/U0-184
