### ISSUE TITLE
1.5 Create slider for landing page

### ISSUE THREAD

**Issue by asya982** [Team-Alexander/frontend#18]
### Desription
1. create slider with 9 talents (view - 3)(( GET request to the server for 9 talents))
2. add button "View all talents" under slider - link to talent's homepage
3. Styles for slider

#### Design

![Image](https://user-images.githubusercontent.com/105641724/227343904-900dcbf0-3041-4d37-880c-8eec55f17762.png)

[Link to Figma](https://www.figma.com/file/XOIDAKeJY6P6Rr4JUTPr2D/UpTalent?node-id=0%3A1&t=ECIUiF5mMXX9XBVM-1)

**Comment by Miroslav-Shashkin** [comment]
@asya982 

- [x] Bug-28 : https://uptalent.atlassian.net/browse/U0-64
- [x]  Bug-35 : https://uptalent.atlassian.net/browse/U0-79
- [x] Bug-39 : https://uptalent.atlassian.net/browse/U0-91
- [x] Bug-86 :  https://uptalent.atlassian.net/browse/U0-161
- [x] Bug-94 : https://uptalent.atlassian.net/browse/U0-169
