### ISSUE TITLE
1.3 Create pagination on Talent's Homepage

### ISSUE THREAD

**Issue by ira-bibik** [Team-Alexander/frontend#22]
### Description
Create pagination for list of talents on Talent's Homepage
add button font-size 10px;

#### Design

![Image](https://user-images.githubusercontent.com/114294333/226351769-8354d598-a7c7-406a-9669-af4986e5f976.png)

[Link to Figma](https://www.figma.com/file/XOIDAKeJY6P6Rr4JUTPr2D/UpTalent?node-id=0%3A1&t=ECIUiF5mMXX9XBVM-1)

**Comment by Miroslav-Shashkin** [comment]
@asya982 

- [ ] Bug-16: https://uptalent.atlassian.net/browse/U0-52?atlOrigin=eyJpIjoiNzZhNzA4NTVjNjQ5NDJhYWJkMTgzNjI3OTU2NDMxOTEiLCJwIjoiaiJ9
- [ ] Bug-19: https://uptalent.atlassian.net/browse/U0-53?atlOrigin=eyJpIjoiZDJkNGU3ZGY2MGJiNDJiYmJhZjNhOGQ1ZGU3MjljODAiLCJwIjoiaiJ9
