### ISSUE TITLE
6.2.1 - edit form for Vacancy

### ISSUE THREAD

**Issue by asya982** [Team-Alexander/frontend#221]
### Description

1. add vacancy tab in sponsors profile
2. make edit /create form for vacancy (title, content, skills)
3. make request for create/edit vacancy
4. make it efficient with proof features

**Comment by Miroslav-Shashkin** [comment]
@asya982 @ira-bibik 
- [x] Bug-87(proof/vacancy) : https://uptalent.atlassian.net/browse/U0-162
- [ ] Bug-95 : https://uptalent.atlassian.net/browse/U0-171
