### ISSUE TITLE
6.1.2 Vacancy

### ISSUE THREAD

**Issue by asya982** [Team-Alexander/frontend#222]
### Description

1.  Main fileds - Title, content, author, skills, status, published time
2. Make 1 component for general info ( Title, author, skills, published time) that links to full info if talanet/sponsor
3. Component with route vacancy/id with full info

**Comment by Miroslav-Shashkin** [comment]
@asya982 @ira-bibik 
- [x] Bug-91 : https://uptalent.atlassian.net/browse/U0-166
- [x] Bug-97 : https://uptalent.atlassian.net/browse/U0-174
- [x] Bug-98 : https://uptalent.atlassian.net/browse/U0-176
