### ISSUE TITLE
6.6.1 Vacancy list

### ISSUE THREAD

**Issue by asya982** [Team-Alexander/frontend#225]
### Description

1. Make distant vacancy page in navbar
2. make Vacancy page withAuth only
3. add filter by skills
4. add sort by date
5. 9 vacancies on every page

**Comment by Miroslav-Shashkin** [comment]
@ira-bibik @asya982 
- [ ] Improvment - 3 : https://uptalent.atlassian.net/browse/U0-170
- [x] Improvment - 4 : https://uptalent.atlassian.net/browse/U0-173
