### ISSUE TITLE
6.2.2 Vacancies list on Sponsor's page

### ISSUE THREAD

**Issue by ira-bibik** [Team-Alexander/frontend#226]
### Description
1. Make tab on Sponsor's page for list of own vacancies(general info).
2.  Add ability to go on page with full info about vacancy.

**Comment by Miroslav-Shashkin** [comment]
@ira-bibik @asya982 
- [x] Bug-90 : https://uptalent.atlassian.net/browse/U0-165
- [x] Bug-96 : https://uptalent.atlassian.net/browse/U0-172
