### ISSUE TITLE
7.1.1 - Response form for vacancy

### ISSUE THREAD

**Issue by asya982** [Team-Alexander/frontend#242]
### Description
- Button "Apply" in vacancy full info
- Form with 2 fields: 
  - Contact info (by default - talent's email) (Add regexp for matching phone number pattern or email in field contact_info)
  - Cover letter (textfield multiline) with placeholder
- Submit with confirmation message
- Response must be seen by talent under the full vacancy 
- Request -

**Comment by Miroslav-Shashkin** [comment]
@asya982 @ira-bibik 

- [x] Bug-99 : https://uptalent.atlassian.net/browse/U0-177
- [x] Bug-100 : https://uptalent.atlassian.net/browse/U0-178
