### ISSUE TITLE
7.2.1 - Response general

### ISSUE THREAD

**Issue by asya982** [Team-Alexander/frontend#243]
### Description
1. Content:
- title vacancy;
- author of vacancy;
- response status. 
2. Delete button (only if status Approved/Denied)
3. OnClick - Redirects to full vacancy page

**Comment by Miroslav-Shashkin** [comment]
@asya982 @ira-bibik 

- [ ] Bug- 102 : https://uptalent.atlassian.net/browse/U0-182
