### ISSUE TITLE
7.4.1 - Sponsor controlls on response

### ISSUE THREAD

**Issue by asya982** [Team-Alexander/frontend#246]
### Description
- 2 buttons on response - approve/denied
- After click on one of them - form is showed
-  **Common features**:
  - Textfield with multiline - for feedback
  - Submit and cancel buttons
- Only **approved** feature:
  - Contact info
- Ability to delete approved or denied response

**Comment by Miroslav-Shashkin** [comment]
@asya982 @ira-bibik 

- [ ] Bug - 103 : https://uptalent.atlassian.net/browse/U0-183
