### ISSUE TITLE
1.1 Create component General talent

### ISSUE THREAD

**Issue by asya982** [Team-Alexander/frontend#5]
### Desription
1. General info about talent
2. Add styles to component of talent
3. Set up MUI theme
4. Max seen skill labels are limited to 3

#### Design

![Image](https://user-images.githubusercontent.com/105641724/226388603-40c19610-4f72-4e26-8e37-a6234fb1197a.png)

[Link to Figma](https://www.figma.com/file/XOIDAKeJY6P6Rr4JUTPr2D/UpTalent?node-id=0%3A1&t=ECIUiF5mMXX9XBVM-1)

**Comment by Miroslav-Shashkin** [comment]
Bug report [https://uptalent.atlassian.net/browse/U0-29?atlOrigin=eyJpIjoiY2M1YzkwZmFmYjhhNDAxNGJlZGRiZDllNTQwNDMyZGMiLCJwIjoiaiJ9](url)

**Comment by DmytroTeliukov** [comment]
@asya982, @ira-bibik 

- [ ] Bug-81: https://uptalent.atlassian.net/browse/U0-146
