### ISSUE TITLE
2.3.1. Creating proofs

### ISSUE THREAD

**Issue by asya982** [Team-Alexander/frontend#75]
### Description
Add form for creating proofs (+styles)
POST request to the server ( to redirect to proff`s id)
PATCH request when saved changes with status draft
Buttons:
-cancel (discard changes)
- to save (would be saved as draft)
Validation: name of the proof is required, max - 255; content - 5k max
Pop-up succesful or error message

**Comment by Miroslav-Shashkin** [comment]
@asya982 
@gleblitvinenko 
- [ ] https://uptalent.atlassian.net/browse/U0-62
